CREATE TABLE GRAPHIC_NOVEL (
    GN_NAME VARCHAR(40),
    AUTHOR VARCHAR(20),
    ILLUSTRATOR VARCHAR(20),
    RELEASE_DATE DATE,
    PUBLISHER VARCHAR(20),
    CONSTRAINT GRAPHIC_NOVEL_PK PRIMARY KEY (GN_NAME)
);

CREATE TABLE AUTHOR_ILLUSTRATOR (
    NAME VARCHAR(20),
    DATE_OF_BIRTH DATE,
    TYPE VARCHAR(15),
    GENDER VARCHAR(10),
    PUBLISHER VARCHAR(20),
    CONSTRAINT WHICH_TYPE CHECK ((TYPE = 'AUTHOR') OR (TYPE = 'ILLUSTRATOR') 
        OR (TYPE = 'BOTH')),
    CONSTRAINT AUTHOR_GENDER CHECK ((GENDER = 'MALE') OR (GENDER = "FEMALE")
        OR (GENDER = 'NON-BINARY')),
    CONSTRAINT AUTHOR_ILLUSTRATOR_PK PRIMARY KEY (AUTHOR_NAME)
);

CREATE TABLE CHARACTER (
    ID INT,
    NAME VARCHAR(20),
    GN_NAME VARCHAR(40),
    GENDER VARCHAR(10),
    CONSTRAINT CHARACTER_GENDER CHECK ((GENDER = 'MALE') OR (GENDER = "FEMALE")
        OR (GENDER = 'NON-BINARY')),
    CONSTRAINT CHARACTER_PK PRIMARY KEY (ID) 
);

CREATE TABLE PUBLISHER (
    NAME VARCHAR(20),
    LANGUAGE VARCHAR(10),
    GN_NAME VARCHAR(40),
    LOCATION VARCHAR(40),
    DATE_FOUNDED DATE,
    CONSTRAINT PUBLISHER_PK PRIMARY KEY (NAME)
);

CREATE TABLE ADAPTATION (
    ID INT,
    BASED_ON VARCHAR(40),
    NAME VARCHAR(20),
    DEVELOPER VARCHAR(20),
    RATING INT,
    TYPE VARCHAR(20),
    CONSTRAINT ADAPTATION_TYPE CHECK ((TYPE = 'LIVE-ACTION') 
        OR (TYPE = 'ANIMATION')),
    CONSTRAINT ADAPTATION_RATING CHECK (RATING <= 10.00),
    CONSTRAINT ADAPTION_PK PRIMARY KEY (ID)
);

CREATE TABLE AWARD (
    ID INT,
    NAME VARCHAR(40),
    AWARD_NAME VARCHAR(20),
    YEAR_AWARDED DATE,
    TYPE VARCHAR(20),
    CONSTRAINT AWARD_TYPE CHECK ((TYPE = 'LITERATURE') OR (TYPE = 'FILM')),
    CONSTRAINT AWARD_PK PRIMARY KEY (ID)
);

